[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 8, y = 8 }
decorations = "full"

[font]
normal = { family = "JetBrainsMonoNF", style = "Regular" }
size = 11.0

[terminal.shell]
program = "/bin/zsh"

[scrolling]
history = 10000

[mouse]
hide_when_typing = true


[colors.primary]
background = "#121212"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#121212"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#121212"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#121212"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#121212"
background = "#a6adc8"

[colors.hints.start]
foreground = "#121212"
background = "#f9e2af"

[colors.hints.end]
foreground = "#121212"
background = "#a6adc8"

[colors.selection]
text = "#121212"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
