# -> git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# -> tmux source .tmux.conf
# prefix + I to install plugins

# ==========================================
# General settings

set -g mouse on               
set -s escape-time 0         
set -g base-index 1         
set -g pane-base-index 1   
set-window-option -g pane-base-index 1
set-option -g renumber-windows on 

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ==========================================
# Keybindings

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n S-Left  previous-window
bind -n S-Right next-window

# ==========================================
# bddeab
set -g status-style bg="#121212",fg="#888888"
set -g status-justify left        

set -g status-left "#[fg=#1e1e2e,bg=#c9de95,bold] #S #[fg=#c9de95,bg=#121212,nobold] "
set -g status-left-length 20

set -g status-right ""

setw -g window-status-format "#[fg=#888888,bg=#222222] #I:#W "
setw -g window-status-current-format "#[fg=#c9de95,bg=#333333,bold] #I:#W "

set -g pane-border-style fg="#333333"
set -g pane-active-border-style fg="#c9de95"

# ==========================================
# Plugins options

# SessionX 
# --- Personalizacja SessionX ---
set -g @sessionx-window-mode 'on'
set -g @sessionx-bind 'w'                 
set -g @sessionx-window-height '75%'      
set -g @sessionx-window-width '65%'       

set -g @sessionx-pointer-color '#c9de95'   
set -g @sessionx-prompt-color '#c9de95'    
set -g @sessionx-highlight-location-color '#c9de95' 

set -g @sessionx-preview-enabled 'true'    
set -g @sessionx-preview-location 'right' 
set -g @sessionx-preview-ratio '45%'      
set -g @sessionx-filter-smart 'on'        

# Resurrect  Continuum
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# ==========================================
# TPM

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'

run '~/.tmux/plugins/tpm/tpm'
